version: '1'

setup:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform The Setup"
    #env
    source pipeline/scripts/setup.sh
    exit 0

static-scan:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform Static Scan"
    exit 0
    
test:
  abort_on_failure: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform Tests"
    exit 0

containerize:
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform Build"
    source pipeline/scripts/build.sh
    exit 0 

deploy:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform Deploy to dev"
    exit 0 

sign-artifact:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform Sign Artifact"
    exit 0  
acceptance-test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform Acceptance Test"
    exit 0 

release:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform Release"
    source pipeline/scripts/release.sh
    exit 0 

dynamic-scan:
  dind: true 
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform Dynamic Scan"
    exit 0

scan-artifact:
  dind: true 
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform Scan Artifact"
    exit 0

owasp-zap:
  dind: true 
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:d59863621d3ba1b9bd47f76950c751e842405f9c303d0d4d4298d964b664ee85
  script: |
    #!/usr/bin/env bash
    echo "Perform owasp-zap"
    exit 0 
