---
- hosts: all
  gather_facts: no
  environment: "{{ environment_vars }}"
  vars:
    ansible_remote_tmp: /SYSTEM/tmp/plum
  tasks:
    - name: Clone the zAppBuil repository
      ansible.builtin.git:
        repo: "https://github.com/IBM/dbb-zappbuild.git"
        dest: "{{ansible_remote_tmp}}/ssh/dbb-zappbuild"
        executable: /rsusr/ported/bin/git
        clone: yes
        update: yes

    - name: Clone the application repository
      ansible.builtin.git:
        repo: "{{app_repo}}"
        dest: "{{ansible_remote_tmp}}/ssh/{{app_repo_name}}"
        executable: /rsusr/ported/bin/git
        version: "{{app_branch}}"
        clone: yes
        update: yes
