---
- hosts: all
  gather_facts: no
  environment: "{{ environment_vars }}"
  vars:
    ansible_remote_tmp: /SYSTEM/tmp/pipeline
  tasks:
    - name: Clone the zAppBuil repository
      ansible.builtin.git:
        repo: "https://github.com/IBM/dbb-zappbuild.git"
        dest: "{{ansible_remote_tmp}}/dbb-zappbuild"
        executable: /rsusr/ported/bin/git
        clone: yes
        update: yes

    - name: Clone the sample application repository
      ansible.builtin.git:
        repo: "{{app_repo}}"
        dest: "{{ansible_remote_tmp}}/{{app_repo_name}}"
        executable: /rsusr/ported/bin/git
        version: "{{app_branch}}"
        clone: yes
        update: yes
        
    - name: Build the sample application
      shell: |
        export WORKSPACE=/tmp/pipeline
        export JAVA_HOME=/usr/lpp/java/J8.0_64
        export PATH=/rsusr/ported/bin:$PATH
        /usr/lpp/IBM/dbb/bin/groovyz\
           ${WORKSPACE}/dbb-zappbuild/build.groovy --logEncoding UTF-8 -w ${WORKSPACE}\
           --workDir ${WORKSPACE}/work -f\
           --application {{app_repo_name}} --sourceDir ${WORKSPACE} -h IBMUSER.SAMPLE\
           -p  ${WORKSPACE}/{{app_repo_name}}/application-conf/datasets.properties
